### ISSUE TITLE
Build on OSX

### ISSUE THREAD

**Issue by melMass** [zpelgrims/pota#5]
It might sound silly but after a few tries I wasn't able to compile, I commented out all unused `out_transmittance`, but the linker still failed.

The culprit was the `bin/` folder that **Make** tries to write to is missing from the repo (it's in the .gitignore)

So the steps:

```bash
vim MakeFile # Delete ARNOLD_PATH and use the env one.
mkdir bin
make
```

Thanks for sharing Zeno ! Great experiment.

**Comment by zpelgrims** [comment]
Thanks for pointing this out - I'll add the compile instructions to the readme!

**Comment by zpelgrims** [comment]
Compile instructions added
