### ISSUE TITLE
Object subdivisions not working as expected

### ISSUE THREAD

**Issue by zpelgrims** [zpelgrims/pota#7]
Probably due to a bad raster space estimate, implement camera_ray_reverse function

**Comment by melMass** [comment]
Was about to say that:

**Without Pota**
![](https://i.imgur.com/kQAmq2w.png)

**With Pota**
![](https://i.imgur.com/VaM9fCq.png)

**Comment by zpelgrims** [comment]
As a temporary workaround, setting the adaptive space to "object" from "rasters" avoids this issue. Even with adaptive error at 0. I think this is an arnold core bug, along with me not implementing the ray_reverse camera function.

**Comment by zpelgrims** [comment]
Accidently closed this issue, should defo be open lol

**Comment by zpelgrims** [comment]
I've implemented two versions of camera_ray_reverse(), a super-accurate polynomial optics version and a pinhole approximation. Currently we'll be using the pinhole approximation, as it is better suited because there is always a solution. The backtraced polynomial optics may run into vignetting of the rays which is a problem.
